"""Slot extraction. Two layers, always both available with zero external dependency (NFR-2):

1. DETERMINISTIC TEMPLATE MATCHING (primary). The customer simulator's reply text is not natural
   free-form language -- it is generated by a small set of known, fixed templates in
   evaluator/local_evaluator.py (verified directly from source, see wiki/09_simulator_mechanics.md).
   Since the same evaluator code scores both the public and private session sets, matching those
   exact templates is not overfitting to the dev set -- it's understanding the real, documented
   protocol. This gives near-perfect extraction precision on every turn after the first.
2. GAZETTEER FALLBACK (secondary). Generic keyword/regex matching against the catalog-derived
   gazetteer, for turn 1's free-form opener and as a robustness net if a message doesn't match any
   known template (e.g. a genuinely novel private-set phrasing).

An LLM arbiter is NOT wired here by default -- see intent_router.py and 06_DECISION_LOG.md D-LLM-TIER.
"""
from __future__ import annotations

import re
from typing import Any, Optional

# ---------- known simulator templates (verified against evaluator/local_evaluator.py) ----------
_RE_BUYING_OPENER = re.compile(
    r"^i'?m looking for (?P<category>.+?)\.\s*a key requirement is:\s*(?P<constraint>.+?)\.?\s*$", re.I)
_RE_BROWSING_OPENER = re.compile(
    r"^i'?m looking for (?P<category>.+?),\s*but i'?m still exploring\.?\s*$", re.I)
_RE_OVERRIDE_OPENER = re.compile(
    r"^i'?m looking for (?P<category>.+?)\.\s*(?P<old_value>.+?)\s*$", re.I)
_RE_OVERRIDE_FORCED = re.compile(
    r"^actually,?\s*ignore my earlier preference\.?\s*what i need is:?\s*(?P<new_value>.+?)\.?\s*$", re.I)
_RE_REVEAL = re.compile(
    r"^for that,?\s*what matters is:?\s*(?P<values>.+?)\.?\s*$", re.I)
_RE_NO_ADDITIONAL = re.compile(
    r"^i don'?t have an additional preference for (?P<attribute>.+?)\.?\s*$", re.I)
_RE_BOUNDARY_DECLINE = re.compile(
    r"^i don'?t have a preference for (?P<attribute>.+?);\s*please use your judgment\.?\s*$", re.I)
_RE_GENERIC_NUDGE = re.compile(
    r"^those options are not quite right yet\. ask me about one specific attribute\.?\s*$", re.I)

_PRICE_RE = re.compile(r"(?:under|below|less than|max(?:imum)?|budget(?: around)?)\s*\$?\s*(\d+(?:\.\d+)?)", re.I)
_BARE_PRICE_RE = re.compile(r"\$\s*(\d+(?:\.\d+)?)")

_RESET_CUES = re.compile(r"\b(actually|never mind|instead|forget (?:that|it|the)|not that|no,? i want)\b", re.I)


def classify_value_attribute(value: str, gazetteer: dict[str, set]) -> str:
    """Mirror of the simulator's own classify_constraint() taxonomy -- lets us file a revealed
    value under the right internal slot even when we already know it's "whatever we asked about".

    CORRECTED per codex review (wiki/reviews/phase0-implementation-2026-08-29.md): plain substring
    `in` checks misclassify ordinary text whenever a short gazetteer word occurs inside another word
    -- e.g. "Water Resistant" contains "tan" and was being classified as color=tan. Word-boundary
    regex matching, consistent with catalog.py's _MATERIAL_RE/_COLOR_RE."""
    lowered = value.lower()
    if "budget" in lowered or _PRICE_RE.search(lowered) or _BARE_PRICE_RE.search(lowered):
        return "budget"
    if any(re.search(rf"\b{re.escape(m)}\b", lowered) for m in gazetteer.get("materials", ())):
        return "material"
    if any(re.search(rf"\b{re.escape(c)}\b", lowered) for c in gazetteer.get("colors", ())):
        return "color"
    if any(w in lowered for w in ("size", "sizing", "width", "wide", "narrow")):
        return "size"
    if any(w in lowered for w in ("department", "style", "fit", "sleeve", "neck")):
        return "style"
    if any(w in lowered for w in ("hiking", "running", "gym", "winter", "outdoor", "work")):
        return "use_case"
    return "feature"


def extract_slot_updates(
    user_message: str,
    state,  # DialogState
    gazetteer: dict[str, set],
    turn: int,
) -> dict[str, Any]:
    """Returns {"slot_updates": {...}, "query_terms": [...], "override": {...}|None,
    "exhausted_attribute": str|None, "no_new_info": bool}."""
    msg = user_message.strip()
    slot_updates: dict[str, Any] = {}
    query_terms: list[str] = []
    override: Optional[dict] = None
    exhausted_attribute: Optional[str] = None
    no_new_info = False

    m = _RE_OVERRIDE_FORCED.match(msg)
    if m:
        new_value = m.group("new_value").strip()
        attr = classify_value_attribute(new_value, gazetteer)
        override = {"cleared_category_dependent": True, "new_value": new_value, "attribute": attr}
        slot_updates[attr] = new_value
        query_terms.append(new_value)
        return _finish(slot_updates, query_terms, override, exhausted_attribute, no_new_info)

    m = _RE_BUYING_OPENER.match(msg)
    if m:
        slot_updates["category"] = m.group("category").strip()
        constraint = m.group("constraint").strip()
        attr = classify_value_attribute(constraint, gazetteer)
        slot_updates[attr] = constraint
        query_terms.extend([slot_updates["category"], constraint])
        return _finish(slot_updates, query_terms, override, exhausted_attribute, no_new_info)

    m = _RE_BROWSING_OPENER.match(msg)
    if m:
        slot_updates["category"] = m.group("category").strip()
        query_terms.append(slot_updates["category"])
        return _finish(slot_updates, query_terms, override, exhausted_attribute, no_new_info)

    m = _RE_REVEAL.match(msg)
    if m:
        # The simulator only ever reveals values that already classify to the asked attribute
        # (verified in wiki/09_simulator_mechanics.md) -- but self-caught before this ran: if two
        # values are revealed and we blindly force BOTH into state.slots[last_asked_attribute],
        # the second silently overwrites the first (slots hold one value per key). Classify each
        # value independently and only fall back to last_asked_attribute when the value's own
        # classification is the generic catch-all ("feature") -- preserves distinct attribute
        # slots when the private set's actual phrasing varies, without losing information for the
        # common single-attribute-per-turn case.
        raw_values = [v.strip() for v in m.group("values").split(";") if v.strip()]
        target_attr = state.last_asked_attribute
        for v in raw_values:
            classified = classify_value_attribute(v, gazetteer)
            attr = target_attr if (classified == "feature" and target_attr and target_attr not in ("other", None)) else classified
            slot_updates[attr] = v
            if attr == "budget":
                # Two representations exist for a reason: "budget" (raw disclosed text, for
                # display/logging) and "budget_max" (parsed float, what retrieval.py's hard-filter
                # and metadata_rank actually read) -- keep both in sync here rather than let the
                # gazetteer fallback be the only path that ever populates budget_max.
                parsed = _parse_price(v)
                if parsed is not None:
                    slot_updates["budget_max"] = parsed
            query_terms.append(v)
        return _finish(slot_updates, query_terms, override, exhausted_attribute, no_new_info)

    m = _RE_NO_ADDITIONAL.match(msg)
    if m:
        exhausted_attribute = m.group("attribute").strip().lower()
        no_new_info = True
        return _finish(slot_updates, query_terms, override, exhausted_attribute, no_new_info)

    m = _RE_BOUNDARY_DECLINE.match(msg)
    if m:
        exhausted_attribute = m.group("attribute").strip().lower()
        no_new_info = True
        return _finish(slot_updates, query_terms, override, exhausted_attribute, no_new_info)

    if _RE_GENERIC_NUDGE.match(msg):
        no_new_info = True
        return _finish(slot_updates, query_terms, override, exhausted_attribute, no_new_info)

    # Turn-1 intent_override opener, or genuinely novel phrasing: fall back to generic extraction.
    m = _RE_OVERRIDE_OPENER.match(msg)
    if m:
        slot_updates["category"] = m.group("category").strip()
        query_terms.append(m.group("old_value").strip())

    _gazetteer_fallback_extract(msg, gazetteer, slot_updates, query_terms)

    if _RESET_CUES.search(msg) and turn > 1:
        override = {"cleared_category_dependent": True, "new_value": msg, "attribute": None}

    query_terms.append(msg)
    return _finish(slot_updates, query_terms, override, exhausted_attribute, no_new_info)


def _parse_price(text: str) -> Optional[float]:
    m = _PRICE_RE.search(text) or _BARE_PRICE_RE.search(text)
    if not m:
        return None
    try:
        return float(m.group(1))
    except ValueError:
        return None


def _gazetteer_fallback_extract(msg: str, gazetteer: dict, slot_updates: dict, query_terms: list) -> None:
    lowered = msg.lower()
    for color in gazetteer.get("colors", ()):
        if re.search(rf"\b{re.escape(color)}\b", lowered):
            slot_updates.setdefault("color", color)
            break
    for material in gazetteer.get("materials", ()):
        if re.search(rf"\b{re.escape(material)}\b", lowered):
            slot_updates.setdefault("material", material)
            break
    parsed_price = _parse_price(lowered)
    if parsed_price is not None:
        slot_updates.setdefault("budget_max", parsed_price)


def _finish(slot_updates, query_terms, override, exhausted_attribute, no_new_info) -> dict[str, Any]:
    return {
        "slot_updates": slot_updates,
        "query_terms": [t for t in query_terms if t],
        "override": override,
        "exhausted_attribute": exhausted_attribute,
        "no_new_info": no_new_info,
    }


_CATEGORY_DEPENDENT_SLOTS = ("color", "size", "style", "material")


def apply_extraction(state, extraction: dict[str, Any], turn: int) -> None:
    """Mutates `state` in place from an extract_slot_updates() result -- override handling,
    slot writes, and exhausted-attribute bookkeeping all live here so agent.py stays a thin loop."""
    override = extraction.get("override")
    if override and override.get("cleared_category_dependent"):
        cleared = []
        for key in _CATEGORY_DEPENDENT_SLOTS:
            if key in state.slots:
                cleared.append(key)
                state.slots.pop(key, None)
                state.slot_confidence.pop(key, None)
        state.override_history.append({
            "turn": turn, "cleared": cleared, "new_value": override.get("new_value"),
        })
        # accumulated_terms is a flat list with no per-term attribution, so a surgical removal of
        # just the stale category's terms isn't possible -- reset it rather than let retrieval
        # keep searching partly for the abandoned category alongside the new one. The category
        # slot itself (if still known) and the override's new value seed the reset list.
        state.accumulated_terms = [t for t in (state.slots.get("category"), override.get("new_value")) if t]
        # CORRECTED per codex review: preference vectors were left untouched on a forced override,
        # so the EMA update kept most of the embedding learned from the just-abandoned preference
        # and its boost (weighted lam/mu in preference.py) is large relative to RRF scores --
        # post-override ranking stayed biased toward the old, explicitly-rejected intent. A forced
        # override is a hard pivot, not a gradual drift, so it gets the same hard reset as slots.
        state.pref_vector_pos = None
        state.pref_vector_neg = None
        state.multi_interest = None  # Phase 2.1: same hard-reset reasoning applies to hypothesis vectors

    for key, value in extraction.get("slot_updates", {}).items():
        state.slots[key] = value
        state.slot_confidence[key] = "confirmed"
        state.slot_last_seen_turn[key] = turn

    exhausted = extraction.get("exhausted_attribute")
    if exhausted:
        state.exhausted_attributes.add(exhausted)

    # Self-caught before this ran: retrieval was originally built from ONLY the current turn's
    # extracted terms, so a "no new info" turn (e.g. "I don't have an additional preference for
    # X") would search with just that uninformative reply text instead of everything learned so
    # far. Accumulate across the whole session; retrieval reads this, not the per-turn delta.
    for term in extraction.get("query_terms", []):
        if term not in state.accumulated_terms:
            state.accumulated_terms.append(term)
