"""Builds submission/ per docs/submission_rules.md's recommended layout and
implementation/05_BUILD_PLAN.md's Phase 5.2 requirements. Regenerates the directory from scratch
each run (idempotent) -- submission/ is a build artifact, not hand-edited, and gitignored like
external/.

Bundles model weights and the precomputed catalog embedding cache so the submission is fully
self-contained: official scoring may run with network access disabled (docs/submission_rules.md),
and a from-scratch encode of the 50K-item catalog showed inconsistent throughput in dev (D-EMBED-CACHE).

Usage: python tools/build_submission.py
Requires: the dense/cross-encoder models already cached locally (sentence-transformers loads them
with HF_HUB_OFFLINE=1 below -- no network call if already cached; fails loudly if not, rather than
silently downloading a possibly-different model version into the bundle).
"""
from __future__ import annotations

import os
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SUBMISSION_DIR = REPO_ROOT / "submission"
EMBEDDINGS_CACHE = REPO_ROOT / "external" / "techjam-conversational-search" / "data" / "_catalog_embeddings.npz"
README_SOURCE = REPO_ROOT / "docs" / "SUBMISSION_README.md"

AGENT_PY = '''# GENERATED by tools/build_submission.py -- do not hand-edit, re-run that script instead.
import sys
import pathlib

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent / "src"))
from copilot.agent import Agent  # noqa: E402,F401
'''

# Deliberately minimal: only what the guaranteed (no-API-key) path needs. anthropic/python-dotenv
# are dev-only conveniences for the optional LLM booster (never a hard dependency, D-LLM-TIER) --
# omitted here so the submission's declared dependencies match exactly what it actually requires,
# and installation can't fail on a network-disabled scorer trying to fetch an unused package.
REQUIREMENTS_TXT = """numpy>=2.0
sentence-transformers>=6.0
"""


def _copy_source() -> None:
    src_dir = SUBMISSION_DIR / "src" / "copilot"
    shutil.copytree(
        REPO_ROOT / "src" / "copilot", src_dir,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
    )
    print(f"Copied src/copilot -> {src_dir}")


def _write_agent_and_requirements() -> None:
    (SUBMISSION_DIR / "agent.py").write_text(AGENT_PY, encoding="utf-8")
    (SUBMISSION_DIR / "requirements.txt").write_text(REQUIREMENTS_TXT, encoding="utf-8")
    print("Wrote agent.py and requirements.txt")


def _copy_readme() -> None:
    if not README_SOURCE.exists():
        print(f"WARNING: {README_SOURCE} not found -- submission will ship without a README.")
        return
    shutil.copy2(README_SOURCE, SUBMISSION_DIR / "README.md")
    print(f"Copied README from {README_SOURCE}")


def _bundle_models() -> None:
    os.environ["HF_HUB_OFFLINE"] = "1"  # never silently fetch a possibly-different model version
    from sentence_transformers import CrossEncoder, SentenceTransformer

    models_dir = SUBMISSION_DIR / "models"
    dense_dir = models_dir / "bge-small-en-v1.5"
    cross_dir = models_dir / "ms-marco-MiniLM-L-6-v2"

    SentenceTransformer("BAAI/bge-small-en-v1.5").save(str(dense_dir))
    print(f"Bundled dense model -> {dense_dir}")
    CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2").save(str(cross_dir))
    print(f"Bundled cross-encoder -> {cross_dir}")


def _bundle_embedding_cache() -> None:
    # CORRECTED per codex review (2026-08-30): this used to only warn and return successfully when
    # the cache was missing, producing a submission that LOOKS built but silently lacks the asset
    # Phase 5.2 explicitly requires -- official scoring would then hit the ~14.5-minute full-catalog
    # recompute with no indication anything was wrong until it was too late to fix. Treat this as a
    # hard build failure instead: a submission without the cache is not a valid build.
    if not EMBEDDINGS_CACHE.exists():
        raise SystemExit(
            f"BUILD FAILED: {EMBEDDINGS_CACHE} not found. Run the evaluator once first (it computes "
            "and caches this automatically) before building the submission -- without it, official "
            "scoring would hit a ~14.5-minute full-catalog recompute on first use."
        )
    data_dir = SUBMISSION_DIR / "data"
    data_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(EMBEDDINGS_CACHE, data_dir / EMBEDDINGS_CACHE.name)
    print(f"Bundled catalog embedding cache -> {data_dir / EMBEDDINGS_CACHE.name}")


def main() -> None:
    if SUBMISSION_DIR.exists():
        shutil.rmtree(SUBMISSION_DIR)
    SUBMISSION_DIR.mkdir(parents=True)

    _copy_source()
    _write_agent_and_requirements()
    _copy_readme()
    _bundle_models()
    _bundle_embedding_cache()

    print(f"\nsubmission/ built at {SUBMISSION_DIR}")


if __name__ == "__main__":
    main()
