"""(Re)generates the evaluator shim at external/techjam-conversational-search/starter/agent.py.

Why this exists (see implementation/04_SYSTEM_DESIGN.md D-PACKAGING, codex-review-corrected):
`external/techjam-conversational-search/` is entirely gitignored (it's the organizer's vendor
clone), so a hand-edited shim file living inside it is never actually committed -- a fresh clone +
re-setup would silently regenerate the *original* weak BM25 starter with no shim at all. Run this
script (idempotent, cheap) as part of setup and again whenever `tools/run_eval.py` runs, so a fresh
checkout always gets correctly wired to the real agent in src/copilot/.

Usage: python tools/install_shim.py
"""
from __future__ import annotations

from pathlib import Path

SHIM = '''# GENERATED by tools/install_shim.py -- do not hand-edit, re-run that script instead.
import sys, pathlib
_ROOT = pathlib.Path(__file__).resolve().parents[3]  # .../v1 (repo root)
sys.path.insert(0, str(_ROOT / "src"))
from copilot.agent import Agent  # noqa: E402,F401
'''


def main() -> None:
    target = Path("external/techjam-conversational-search/starter/agent.py")
    if not target.parent.exists():
        raise SystemExit(
            f"{target.parent} does not exist -- clone the participant repo first "
            "(see wiki/07_external_resources.md)."
        )
    target.write_text(SHIM, encoding="utf-8")
    print(f"Wrote shim to {target}")


if __name__ == "__main__":
    main()
